version: "3.8"

services:

  my-sba-vehicle:
    image: openjdk:17
    container_name: vehicleSerProIoT
    ports:
      - 8082:8080
      - 8002:8000
    expose:
      - "8002"
    depends_on:
      - my-db-vehicle
    networks:
      - my-net
    volumes:
      - "${PWD}/build/libs/VehicleServiceProject-0.0.1-SNAPSHOT.jar:/app/app.jar"
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  my-db-vehicle:
    image: mongo:5.0
    container_name: mongodbIoT-Vehicle
    ports:
      - 27019:27017
    networks:
      - my-net
#networks:
#  shared-net:
#    external: true
networks:
  my-net:
    driver:
      "bridge"
